---
title: "notes"
format: docx
editor: visual
---

March 20

urban-rural split

purpose: exploration of disparity metrics; practical implications of inclusion for chrr where we care about all 3000 counties

in the context of a single measure

## March 18

thursday - send keith the findings ; keith and i will write together on thurs/fri ; invite EB to this too

draft to heni and ganhua on monday ; send to leadership to review by wednesday (michael) ; submit friday after michael's approval

things i see as next steps: check the CIs and remove unstable estimates ; kg thinks income might be most complete, need to check CI stability

switch abstract to be more descriptive ; home ownership is a case example, descriptive comparisions, but no models ; correlations, magnitude, practical considerations (rurality, etc) - purpose is to compare ; title: within county disparities measured across three domains (if chrr was thinking about this, what would we want to know?)

TABLE 1: compare magnitudes

table 2: correlations

figure 1: maps of dist and missingness

commentary on missingness , practical implications , urbanicity

-   do natality files have tract? PROBABLY NOT we have edu and race......(we would need to amend the DUA) harrison quick is simulating tract level vitality data and he has real tract level for MN and PA

redo the descriptives with paired down data

need to better understand the relationships between urbanicity and CT level disparities

multilevel modeling to answer this??? like the Dubowitz paper

-   for each X increase in CT income, there is X change in county level race disparity

-   For each X increase in CT income, there is X change in county level income disparity

## March 5, 2025

-   how does Jun summarize his comparisons and his findings from various models/methods in the simulation paper? are there other papers of Jun's that are relevant / might spark ideas?

-   Should we assess income disparities instead since they are the largest? but are census tract disparities an appropriate proxy since they are more readily available? more clearly defined?

-   Work towards abstract deadline for APHA March 27

-   put results on p drive

-   clarify partial corr discordance with multiple regression - this will inform next steps

-   decomposition of thiels index - not useful yet...

## Feb 2, 2025

-   Clarify the research question

    -   What are census tract disparities capturing?

    -   What has been done to capture disparities using CT level data previously? 

    -   If we measure disparity at the CT level, how much disparity in other domains are we capturing? 

    -   For now, we are not interested in incorporation of disparity into ranks / clusters; that is a separate research question. 

-   Analyze data: P:\\CH-Ranking\\Research\\Disparity Measurement\\Census Tract Disparity Measurement

    -   Initial thoughts:

        -   regression with CT level disparity as a covariate to "adjust" a relationship between a well-established health factor and a health outcome (or cluster) 

            -   This will tell us how much of the relationship between income (for example) and health can be explained by CT disparities ; could do the same with edu and/or race (though race is not ideal because we would probably have to pick just one) 

        -   Regression with CT level disparity as an outcome with income and race as predictors 

            -   This will tell us if income or race disparities is a stronger predictor of census tract disparities  

    -   Decomposition - find more info in the cancer disparities paper 

        -   Can we decompose CT disparities into race and income components ? 

-   Run analyses by Ron? Paul? Amy? 

## initial meeting

papers to read: messer 2008, harper 2008, firebaugh 2003

white paper output notes/questions:

-   within reach: census tract disparities for 5 measures of length and quality of life - what are these 5??

-   a dozen subgroup disparity metrics were eval'd using ct level data for self reported fair/poor health and life expectancy - need to figure out which dozen disparity metrics and also why these two vars

-   narrowed down the metrics by comparing county ranks based on performance in various metrics but ranks only deviated by less than 5 from the avg rank across metrics (this is a lil confusing but i think this is saying that regardless of method, the ranks don't change if/when we account for disparity? how exactly was disparity accounted for? ) can i find this code???

-   pop avg as reference pt - can't discern direction easily

-   inequality aversion - heavily weight large departures from reference; need to be careful if pop weighted to avoid over emphasizing extreme disparities in small reference groups

-   pop weighting - almost always good

-   relative v absolute - absolute are easier to communicate / act on; best if combined w a measure of overall health (like a rank adjustment)

-   absolute: bgv relative: theils, mean log deviation (MLD) ; theils more heavily weights the deviation from the mean while mld more heavily weights pop

-   proportion CTs: need a min of 2 in order to use our methods - 93% of counties have at least 2 CTs ; no evidence that counties w few CTs are biased

-   HIGHLIGHTED: need analyses on the assoc between CTs and other social groups of interest (race, edu, income) ; what measures of assoc or methods to use to do this? (this is the q keith asked me to do lit review on!!!)

-   weighted mean of CT versus weighted SD of CT - is this population weighted???

-   check out the harvard geographic insights and the inequality adjusted human development index

    -   <https://hdr.undp.org/inequality-adjusted-human-development-index#/indicies/IHDI>

    -   <https://geographicinsights.iq.harvard.edu/CongressionalDistrict-LifeExpectancy>

justification of census tracts

health equity quadrants

heni's papers

jun's analyses which compare disparity - ask elizabeth for these drafts (there are 2 papers)

strategic implementation and how to communicate

how to include in rankings

mostly need to make a lot of decisions and justify them / compromise

Based on the reading in Heni's folder

-   simple regression models between disparities and some other measure of health (cluster??)

-   correlation between each of these disparity metrics themselves

-   model between poverty (or some other well established and simple metric - could be income, edu, etc) and health and "adjust" for the disparity (ie as a covariate)

    -   model between income and health (cluster) and adjust specifically for income disparity

        -   then we can say that the relationship between income and health is XXX explained by disparities in income

    -   model between edu and health (cluster) and adjust for race disparity

        -   then we can say that the relationship between edu and health is xxx explained by racial disparities (hmmmm maybe not so useful )

        -   

specific question = if we measure disparity at the CT level, how much disparity in other domains are we capturing

this table: P:\CH-Ranking\Research\Disparity Measurement\Census Tract Disparity Measurement\\2024 Digging Deeper Table_04252024.xlsx ; tab: Field Comparison_6 Disagg

homeownership was decided to be pilot measure because no modeling, no income already included

decomposition of disparities!!! need to find this in the cancer disparities paper

is it okay to measure disparities at the CT level and what else are we capturing with these metrics?
